pipeline:

  build-docker-image:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t pttg-ip-smoke-tests .
    when:
      branch: master
      event: push

  install-docker-image:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_password
    commands:
      - docker login -u="ukhomeofficedigital+pttg_ip_smoke_tests" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag pttg-ip-smoke-tests quay.io/ukhomeofficedigital/pttg-ip-smoke-tests:build-$${DRONE_BUILD_NUMBER}
      - docker push quay.io/ukhomeofficedigital/pttg-ip-smoke-tests:build-$${DRONE_BUILD_NUMBER}
    when:
      branch: master
      event: push

  clone-kube-project:
    image: plugins/git
    commands:
      - git clone https://github.com/UKHomeOffice/kube-pttg-ip-smoke-tests.git
      - cd kube-pttg-ip-smoke-tests
      - git checkout $${KUBE_BRANCH:=master}
    when:
      event: [push, deployment]

  smoke-test:
    image: quay.io/ukhomeofficedigital/kd:v0.8.0
    commands:
      - cd kube-pttg-ip-smoke-tests
      - ./deploy.sh
    when:
      event: [deployment, push]
